function R0=computeR0VsTemperature(spp,pars,T)
%
% R0=computeR0VsTemperature(spp,pars,T)
%
% Matlab function to compute R0 as a function of temperature for different
% strains of epizootic haemorrhagic disease virus in deer using random
% sampling from the (joint) posterior distribution
%
% Inputs:
% spp - string indication species being considered ('Cattle' or 'Deer')
% pars - array of replicated, sampled parameters generated by the function
%        samplePosteriors.m (rows-samples; cols-see samplePosteriors.m for
%        details)
% T - vector of temperatures at which to compute R0
%
% Outputs:
% R0 - value of R0 for each sample (rows) at each temperature (columns)

% Compute the biting rate at each temperature
a=max(0,repmat(pars(:,4),1,length(T)).*repmat(T,size(pars,1),1).*...
        (repmat(T,size(pars,1),1)-repmat(pars(:,5),1,length(T))).*...
        sqrt(42-repmat(T,size(pars,1),1)));

% Compute the reciprocal of the mean EIP at each temperature
if strcmp(spp,'Cattle')==1
    nu=max(0,repmat(pars(:,7),1,length(T)).*...
             (repmat(T,size(pars,1),1)-repmat(pars(:,8),1,length(T))));
elseif strcmp(spp,'Deer')==1
    nu=max(0,repmat(pars(:,9),1,length(T)).*...
             (repmat(T,size(pars,1),1)-repmat(pars(:,10),1,length(T))));
end

% Compute the vector mortality rate at each temperature
if strcmp(spp,'Cattle')==1
    mu=repmat(pars(:,10),1,length(T)).*exp(repmat(pars(:,11),1,length(T)).*...
                                           repmat(T,size(pars,1),1));
elseif strcmp(spp,'Deer')==1
    mu=repmat(pars(:,12),1,length(T)).*exp(repmat(pars(:,13),1,length(T)).*...
                                           repmat(T,size(pars,1),1));
end

% Compute the duration of viraemia allowing for any disease-associated
% mortality
if strcmp(spp,'Cattle')==1
    durV=repmat(pars(:,6),1,length(T));
elseif strcmp(spp,'Deer')==1
    pars(:,6)=1./pars(:,6); % convert mean to rate
    durV=(1./pars(:,8)).*(1-(pars(:,6).*pars(:,7)./...
                            (pars(:,6).*pars(:,7)+pars(:,8))).^pars(:,7));
    durV=repmat(durV,1,length(T));
end

% Extract the remaining temperature-independent parameters
b=repmat(pars(:,1),1,length(T));
beta=repmat(pars(:,2),1,length(T));
m=repmat(pars(:,3),1,length(T));
if strcmp(spp,'Cattle')==1
    k=repmat(pars(:,9),1,length(T));
elseif strcmp(spp,'Deer')==1
    k=repmat(pars(:,11),1,length(T));
end

% Compute the proportion of vectors completing the EIP
PrEIP=(k.*nu./(k.*nu+mu)).^k;

% Compute R0 for the parameter values
K_HV=b.*a.*PrEIP./mu;
K_VH=beta.*a.*m.*durV;
R0=sqrt(K_HV.*K_VH);
